// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC.Admin {
    public class SharedController {

        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string _CkeditorScripts = "~/Areas/Admin/Views/Shared/_CkeditorScripts.cshtml";
            public readonly string _DashboardLayout = "~/Areas/Admin/Views/Shared/_DashboardLayout.cshtml";
            public readonly string _LeftMenu = "~/Areas/Admin/Views/Shared/_LeftMenu.cshtml";
            public readonly string _Links = "~/Areas/Admin/Views/Shared/_Links.cshtml";
            public readonly string _Scripts = "~/Areas/Admin/Views/Shared/_Scripts.cshtml";
            static readonly _EditorTemplates s_EditorTemplates = new _EditorTemplates();
            public _EditorTemplates EditorTemplates { get { return s_EditorTemplates; } }
            public partial class _EditorTemplates{
                public readonly string _Notifications = "_Notifications";
            }
            static readonly _JsScripts s_JsScripts = new _JsScripts();
            public _JsScripts JsScripts { get { return s_JsScripts; } }
            public partial class _JsScripts{
                static readonly _Sections s_Sections = new _Sections();
                public _Sections Sections { get { return s_Sections; } }
                public partial class _Sections{
                    public readonly string TableScript = "~/Areas/Admin/Views/Shared/JsScripts/Sections/TableScript.cshtml";
                }
            }
            static readonly _SectionsPartials s_SectionsPartials = new _SectionsPartials();
            public _SectionsPartials SectionsPartials { get { return s_SectionsPartials; } }
            public partial class _SectionsPartials{
                public readonly string _IndexGrid = "~/Areas/Admin/Views/Shared/SectionsPartials/_IndexGrid.cshtml";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
