// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Site.Areas.Admin.Controllers {
    public partial class SectionsController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SectionsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult AjaxDataTableHandler() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.AjaxDataTableHandler);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SectionsController Actions { get { return MVC.Admin.Sections; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Sections";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Sections";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string AjaxDataTableHandler = "AjaxDataTableHandler";
            public readonly string Create = "Create";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Index = "Index";
            public const string AjaxDataTableHandler = "AjaxDataTableHandler";
            public const string Create = "Create";
        }


        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Create = "~/Areas/Admin/Views/Sections/Create.cshtml";
            public readonly string Index = "~/Areas/Admin/Views/Sections/Index.cshtml";
            static readonly _BackUp s_BackUp = new _BackUp();
            public _BackUp BackUp { get { return s_BackUp; } }
            public partial class _BackUp{
                public readonly string Index = "~/Areas/Admin/Views/Sections/BackUp/Index.cshtml";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_SectionsController: Site.Areas.Admin.Controllers.SectionsController {
        public T4MVC_SectionsController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult AjaxDataTableHandler(WebSite.Models.JQueryDataTableParametersModel param) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.AjaxDataTableHandler);
            callInfo.RouteValueDictionary.Add("param", param);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Create() {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Create);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Create(WebSite.Models.SectionCreateViewModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Create);
            callInfo.RouteValueDictionary.Add("model", model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
